# Generated by Django 5.2.8 on 2025-11-09 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='El valor de 1 USD en VES', max_digits=8)),
                ('fecha_vigencia', models.DateField(default=django.utils.timezone.now, help_text='Fecha de vigencia de la tasa', unique=True)),
            ],
            options={
                'ordering': ['-fecha_vigencia'],
            },
        ),
    ]
