# Generated by Django 5.2.8 on 2025-11-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasacambio',
            name='valor_euro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='El valor de 1 EUR en VES', max_digits=8, null=True),
        ),
    ]
